### ISSUE TITLE
Extension to more than two choices

### ISSUE THREAD

**Issue by refactoriel** [nicholas-roy/psytrack#11]
Hello,

thanks for the great toolbox!

I was wondering how easy it is to extend this toolbox to include an additional choice. Specifically, I'd like to include omission trials in a 2AFC task.
In the paper it says that it can be done, together with a reference to Bak & Pillow 2018. I guess if it was that simple you would already have included it in this toolbox?

I can think of workarounds using a binary response variable:
1. Discard omission trials (possibly incorporating the number of omitted trials as a regressor)
2. Represent response as correct vs error (omission + wrong choice) instead of choice A vs choice B.

Would that make sense?

Best wishes,
Daniel

**Comment by nicholas-roy** [comment]
Hi Daniel,

Thanks for using PsyTrack! 

Expanding the code to handle a _K_-AFC task (_K_ > 2) is not implemented. However, the reference in the original paper indicates that adding the feature is straightforward in theory and _potentially_ straightforward in practice. Ultimately, it would just take a good amount of time to code up and test (which I have no immediate intentions of doing, though you are of course welcome to give it a shot!).

Your proposed workarounds sound good to me! Either could work, I tend to go with option 1 — but option 2 could be better for you, depending on your goals. Specifically, I discard the omission trials, do not represent them with any additional regressor, but use them in the coding of other history regressors I may be using. For example, if I have a regressor on the Previous Choice, I'll code -1 as a left choice on the previous trial, +1 as a right choice, and 0 if no choice was made on the previous trial (i.e. the previous trial was an omission OR came from the previous session).

Best,
Nick

**Comment by refactoriel** [comment]
Hi Nick,

thanks for your quick and elaborate reply!
I guess I'll try the workarounds first before I spend weeks on trying to extend this toolbox 😉 

Best,
Daniel
