### ISSUE TITLE
Mismatch between bias and bias weights

### ISSUE THREAD

**Issue by jmasis** [nicholas-roy/psytrack#15]
Hi there,

This may be a problem that's due to errors in my implementation, but I got some strange behavior regarding the bias and bias weights that I can't make sense of while fitting some of my rat 2-AFC data. For some context, the rats are previously trained on a visual task, but in these data are seeing blank screens so the stimulus is uninformative. As you'll see below, the stimulus variable weights are 0 precisely because this is the case. The object of using Psytrack is to see what stimulus-independent strategies they might be implementing in order to make their choices.

In short, my doubts are:

1 - I am not sure how to interpret a negative bias weight
-is it L/R?
-is it the presence/absence of bias (in which case a negative value is confusing, as well as a weight when there is no bias)?
-is it bias interacting with the other variables? (this would also be confusing, especially since the paper and documentation notes that bias weights are independent of other variable weights, and this seems to be the case when I run different models)

2 - I am unsure as to why the bias weights seem to have such large magnitude in some cases
-I saw in the paper that large weights can be a red flag, but it is unclear to me what the potential issue could be here

Here are some examples of the strange behavior:

**Example 1**
This animal appears to have a strong positive (rightwards) bias:

![image](https://user-images.githubusercontent.com/6462771/110677867-a7cfd500-81a3-11eb-8deb-4b6b4d952a1d.png)

But, its bias weight is strongly negative:

![image](https://user-images.githubusercontent.com/6462771/110677991-cc2bb180-81a3-11eb-9cbb-b1f1139acc12.png)

From the paper, it seemed like the interpretation of +/- in the bias weights also corresponded to R/L, which makes this result confusing. 

**Example  2**
This other animal appears to have a strong negative bias:

![image](https://user-images.githubusercontent.com/6462771/110678189-06954e80-81a4-11eb-9cbc-4199febbef58.png)

And here, its bias weights are also very strongly negative:

![image](https://user-images.githubusercontent.com/6462771/110678268-1a40b500-81a4-11eb-831e-90d6e74a4dbe.png)

This would seem as expected, except that the magnitude on the bias weights is quite alarming.

**Example 3**
This animal has a strong negative bias:

![image](https://user-images.githubusercontent.com/6462771/110678856-c08cba80-81a4-11eb-97fe-cd1a192b81d8.png)

And quite strangely, the shape of that bias trajectory seems to be tracked almost perfectly by a _different_ variable:

![image](https://user-images.githubusercontent.com/6462771/110678926-d9956b80-81a4-11eb-9f69-95391eaffe09.png)

**Example 4**
This animal has a slight negative bias that then switches to a positive bias:

![image](https://user-images.githubusercontent.com/6462771/110679870-f41c1480-81a5-11eb-8562-323e446a3b5c.png)

The trajectory of its bias weights resembles its bias trajectory, but the weights remain negative:

![image](https://user-images.githubusercontent.com/6462771/110679969-1150e300-81a6-11eb-8bca-122c417b54b2.png)

**Example 5**
As a sanity check, I looked at bias and bias weights in the control sessions with visible stimuli beforehand, and there the results are not as strange, but still somewhat unexpected. For example, this animal seems to have a very slight bias, if any: 

![image](https://user-images.githubusercontent.com/6462771/110680912-32fe9a00-81a7-11eb-8662-ebcd7a82c2ac.png)

And its performance is reliably above chance:

![image](https://user-images.githubusercontent.com/6462771/110681950-60981300-81a8-11eb-95d8-dc8f506863ae.png)

And yet its bias weight is strongly negative and has the largest magnitude out of any variable, including the stimulus:

![image](https://user-images.githubusercontent.com/6462771/110680861-22e6ba80-81a7-11eb-80da-a011f1e98ddf.png)

**Example 6**
This other animal during a control sessions viewing visible stimuli has the following bias:

![image](https://user-images.githubusercontent.com/6462771/110681233-98528b00-81a7-11eb-8cfe-9238182d72be.png)

Which actually seems to interact quite clearly with its performance:

![image](https://user-images.githubusercontent.com/6462771/110682082-8ae9d080-81a8-11eb-9bbf-5e4d92b3ae99.png)

And it appears to be tracked quite well by the bias weights (albeit with large error):

The fact that in this case the bias weights perhaps behave as expected makes me think like there may not necessarily be a problem in my implementation of the model.

![image](https://user-images.githubusercontent.com/6462771/110681262-a4d6e380-81a7-11eb-80aa-3310ed0c989f.png)

Any help would be greatly appreciated! Thank you!

Javier

**Comment by jmasis** [comment]
Hi again!

So I figured out the issue! The problem was appropriate categorical variable coding (i.e. L/R = 1 & 2 (or 0 & 1) for the variable 'y' whereas L/R = -1 & +1 for any 'input' variable). So for example, say you have ten trials with the following responses:

'y' = [ 1  2  2  1  1  2  2  2  1  2 ]

And you would like to check for perseverant behavior one trial back, meaning you displace the response vector by one. When you do this, now L/R must be coded as -1 & +1, _not_ 1 & 2:

'previous_y' = [ 0 -1 +1 +1 -1 -1 +1 +1 +1 -1 ]

Apparently this can create very strange behavior in the fits, so for anyone reading this, make sure to double check this!

Love the package!

Javier

**Comment by jpillow** [comment]
Thanks for the comments, @jmasis!  Glad you figured out the problem, and please let us know if you have any other issues!
