### ISSUE TITLE
Code for population analysis

### ISSUE THREAD

**Issue by elianalousada** [nicholas-roy/psytrack#17]
Hello! Thank you for developing psytrack, it's a pretty cool tool.
I have used it thus far to look individually at the behaviour of my animals, and I am wondering if you have the code available to analyse them as a group. 
Thanks!
Eliana

**Comment by nicholas-roy** [comment]
Hi Eliana,

Apologies for the late reply! I would highly recommend using the code from the Colab notebook associated with the recent _Neuron_ paper (https://tinyurl.com/PsyTrack-colab). There are many examples in there of analyzing many animals at once (though it really is nothing more than just looping through a list of the them sequentially).

Hope that helps!
Nick
