### ISSUE TITLE
Fixing some weights to be constant while allowing others to vary across trials

### ISSUE THREAD

**Issue by SamuelLiebana** [nicholas-roy/psytrack#18]
Hi, thanks for making this code available - it is very useful!

I was wondering whether you have any pointers on how to allow some weights to be constant across trials while have others learnt to vary across trials. I ask this because in Figure 2C of your paper https://www.cell.com/neuron/fulltext/S0896-6273(20)30963-6?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0896627320309636%3Fshowall%3Dtrue you have done this with one of the weights having sigma = 0.

In the current implementation, the inverting of the covariance matrix of the prior (invSigma) would not allow any of the sigmas in hyper to be 0 and I was hence wondering how you achieved this for the figure in the paper.

Thank you in advance!

**Comment by nicholas-roy** [comment]
Thanks for the question, and apologies for the late reply! You can actually check out the associated Colab notebook for the exact code used to produce every figure in the paper: https://tinyurl.com/PsyTrack-colab

More specifically, I think the answer to your question is that I do not set sigma to _exactly_ 0 (for the precise reason you describe), but instead just set it to a very small value (2^-16 I think?) that has the same practical effect as keeping the weight constant.

Hope that helps!
Nick
