### ISSUE TITLE
Advice for mapping weights back to labels

### ISSUE THREAD

**Issue by zashwood** [nicholas-roy/psytrack#7]
Are you able to include some documentation to describe how weights are ordered in `wMode`?  I would have assumed that the ordering of weights in `wMode` and `weights` would be the same, but I don't think that's true in practice.  Instead, I think the rows in `wMode` are the weights when the weight names are ordered alphabetically.  Is this true?  Thanks.

**Comment by nicholas-roy** [comment]
Yes, it's a bit confusing. But `weights` is a dict and so has no order. The
weights in `wMode` are arranged alphabetically.

**Comment by zashwood** [comment]
Ok, thanks.

**Comment by nicholas-roy** [comment]
The documentation and code was updated to make this more clear in the most recent version 1.2.0 — thanks again for the contribution!
