### ISSUE TITLE
Error during pip install using Anaconda on Windows

### ISSUE THREAD

**Issue by guidomeijer** [nicholas-roy/psytrack#8]
When running `pip install psytrack` in an Anaconda shell on a Windows system I get the following error:

`ERROR: Could not install packages due to an EnvironmentError: [WinError 267] The directory name is invalid: 'C:\\Users\\guido\\AppData\\Local\\Temp\\pip-install-sk1sle_r\\psytrack\\psytrack/aux'`

Also directly installing from git did not work.

**Comment by nicholas-roy** [comment]
Windows really hates directories called "aux" apparently -- but this issue
has been fixed in the most recent version.

Any chance you could clear out your temporary files (or do a "pip uninstall
psytrack") and try again?

**Comment by nicholas-roy** [comment]
This is definitely now fixed in the most recent version 1.2.0 — thanks again for the catch!
